### ISSUE TITLE
XP

### ISSUE THREAD

**Issue by Jarweile** [LoggeL/hpfn-SAFT#11]
XP-points werden im UI nicht aufsummiert, es wird immer nur die XP des letzten Getränks angezeigt

**Comment by LoggeL** [comment]
Could repro a variant of this bug and fixed it. Please check if that was the bug you mentioned.

**Comment by LoggeL** [comment]
Still not fixed

**Comment by Jarweile** [comment]
Klappt bei mir jetzt, kp was da war
