### ISSUE TITLE
Striche verschwinden

### ISSUE THREAD

**Issue by Jarweile** [LoggeL/hpfn-SAFT#14]
Wenn man Getränke (bei Firefox auf Desktop) einträgt, und dann auf andere Seite wechselt, dann wieder zurück auf die Homeseite kommt sind die Striche nicht mehr vorhanden

**Comment by LoggeL** [comment]
Kann ich leider nicht reproduzieren 😟
![Repro](https://i.imgur.com/dAHg42C.gif)

**Comment by LoggeL** [comment]
Sollte damit zusammenhängen, dass die Drink Validierung nicht korrekt funktioniert hat.

**Comment by Jarweile** [comment]
Passiert jetzt auch nicht mehr bei mir, ich close das auch mal
