### ISSUE TITLE
XP Leiste bei Abzug von Getränken

### ISSUE THREAD

**Issue by LTDgd** [LoggeL/hpfn-SAFT#16]
Wenn keine Getränke übrig sind und man das Getränk dennoch abzieht, ist der Bestand zwar bei 0 fest, aber XP werden der Leiste noch entsprechend abgezogen

**Comment by LoggeL** [comment]
Der  [-] Knopf wird jetzt gesperrt, wenn keine Striche mehr übrig sind.
