### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by LoggeL** [LoggeL/hpfn-SAFT#17]
The app should now be installable via the Install PWA Button which should give it a more "App-like" experience. Would be nice if you could test and give some feedback :)

**Comment by Jarweile** [comment]
Do not see any install button, how do we use the "Install" feature?

**Comment by LoggeL** [comment]
Ah ye my bad. It currently is palced in the nav bar till I find a better place. It currently pushes the Login button out of the bar 😅
 ![Screenshot_20230703-143432.png](https://github.com/LoggeL/hpfn-SAFT/assets/11969415/5bccdfd0-3730-40ba-a26e-84f39d89d67d)

It will only appear after interacting with the website for ~30 seconds (browser requirement).

**Comment by Jarweile** [comment]
Still can't find the button, even if i interact with the website :(

**Comment by LoggeL** [comment]
After some research I found out that firefox does not support the installation of Progressive Web Apps via that event, that's why the button is not rendered 😢 
It will only work in chromium based browsers.

**Comment by LoggeL** [comment]
Moved the install button. Will leave the feature, as people using Firefox shouldn't notice it missing and people using a chromium based browser might profit from the near native app experience.
