### ISSUE TITLE
Manager function

### ISSUE THREAD

**Issue by Jarweile** [LoggeL/hpfn-SAFT#2]
The user should be able to assign multiple managers (maybe with a tick?)
It has to be clearer that the manager-option on the main page is für Eintragungen für andere Nutzer (vllt Farbcodiert das man nicht bei sich einträgt zur Zeit?)

**Comment by LoggeL** [comment]
Hab die Funktion jetzt umgeschrieben, dass es über das Profilbild abrufbar ist. Hätte gesagt, dass die änderung des Profilbildes und des Nutzernamens reichen sollte, kann aber auch noch gerne eine Farbkodierung einbringen.

Aktuell kann jeder User nur einen Manager bestimmen. Wenn das ein Problem ist, muss ich nochmal die Sturkur ändern.

**Comment by Jarweile** [comment]
Hätte eher gesagt, dass jeder eine Auswahl treffen kann wer zum Eintragen berechtigt ist, wenn das geht.
Ansonsten muss man ja jedes mal wenn jemand eine Eintragung vornehmen soll wieder mit der App interagieren und den Manager wechseln.

Kann man vllt Eintragungen durch andere vom jeweiligen Nutzer freigeben lassen? 
Gäb dann folgende Pipeline:

- User erlaubt anderen Usern ("Managern") das Eintragen von Getränken
- Manager bekommt alle User angezeigt die ihm die Erlaubnis erteilt haben
- Manager wählt User für den ein Getränk eingetragen werden soll und trägt Getränk ein
- User bekommt eine Benachrichtigung / Pop-Up, in dem über die Eintragung informiert wird und kann die Eintragung freigeben bzw. opposen (?)
- Wurden mehrere Getränke eingetragen kommt alles aufs gleiche Popup

Wenn das generell funktionieren würde wäre geil.

**Comment by LoggeL** [comment]
Ja soweit isses ja schon drin. Das einzige was noch fehlt ist die Info an den User, dass der Manager etwas eingetragen hat, bzw. dass jeweils nur ein Manager bestimmt werden kann.

![image](https://github.com/LoggeL/hpfn-SAFT/assets/11969415/96a41747-3426-44fb-89be-fb7211b1d5e3)
![image](https://github.com/LoggeL/hpfn-SAFT/assets/11969415/9dea6fd4-4628-4441-905e-bd3eed4cfb78)

**Comment by LoggeL** [comment]
Maybe try to add multiple in string array? Needs experiment

**Comment by LoggeL** [comment]
Added checkboxes for managers. Not the prettiest solution, but does it's job
