### ISSUE TITLE
Zeitabhängige Preise

### ISSUE THREAD

**Issue by Jarweile** [LoggeL/hpfn-SAFT#21]
Bei Preisänderung von Getränken darf sich der historische Preis von bereits getrunkenen Getränken nicht ändern

**Comment by Jarweile** [comment]
Bei Löschung von Getränken - Last in First out damit nicht falsch bepreiste Getränke gelöscht werden

**Comment by Jarweile** [comment]
Das Geld muss direkt im Tick eingespeichert sein

**Comment by LoggeL** [comment]
Resolved
