### ISSUE TITLE
Newsfeed

### ISSUE THREAD

**Issue by Jarweile** [LoggeL/hpfn-SAFT#24]
News durch Getränkemeister möglich machen: Zb Meldung "Neue Getränke verfügbar" oder so

Zum Beispiel "Bier des Monats"-Infos hinterlegen

Meldung "Kohnszeit" wurde festgelegt automatisch wenn festgelegt werden sollte

**Comment by LoggeL** [comment]
Added simple news. Can be written from database.
Needs tracking who read it to add a notification dot.
