### ISSUE TITLE
Getränk eintragen

### ISSUE THREAD

**Issue by Jarweile** [LoggeL/hpfn-SAFT#3]
+ Die Animationen für + und - Getränk ist jeweils fein, kann man da allerdings für - vllt eine andere als für + machen?
+ Striche müssen angezeigt werden / Anzeige von Änderung der Striche

**Comment by LoggeL** [comment]
Allgemein fehlen noch viele Backend Calls. 
Eine Eintragung muss jeweils in 5 Tabellen eingetragen werden.

**Comment by LoggeL** [comment]
Tabllen für + -
drinks_today
drinks_week
drinks_payment
payments
drinks_total
log

**Comment by LoggeL** [comment]
Added hooks to all dbs. But hooks need to be refined to update the date if required.

**Comment by LoggeL** [comment]
Should be completed. If bugs found repoen
