### ISSUE TITLE
Logs 

### ISSUE THREAD

**Issue by LoggeL** [LoggeL/hpfn-SAFT#8]
Needs pagination and or filter.
Or just guide to backend?

**Comment by Jarweile** [comment]
Der Log ist ja sowieso nur für den Admin?
Dann reicht da eigentlich ein guide zum Backend

**Comment by LoggeL** [comment]
Jo hab mal die letzten 50 Events angezeigt, rest steht im Backend. Dazu gibt's einen Button im Admin Bereich
